import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/extension.ts"],
  target: "es2015",
  external: ["vscode"],
  noExternal: [
    "luxon",
    "lodash",
    "title",
    "execa",
    "@sentry/integrations",
    "@sentry/node",
    "semver",
    "vscode-uri",
    "@dendronhq/api-server",
    "@dendronhq/common-all",
    "cross-path-sort",
    "@dendronhq/common-server",
    "@dendronhq/engine-server",
    "@dendronhq/pods-core",
    "@dendronhq/api-server",
    "fs-extra",
    "is-url",
    "luxon",
    "lodash",
    "markdown-it",
    "open",
    "open-graph-scraper",
    "path-browserify",
    "process",
    "query-string",
    "semver",
    "stream-browserify",
    "stream-http",
    "string-similarity",
    "textextensions",
    "title",
    "unist-util-visit",
    "util",
    "vscode-languageclient",
  ], // Explicitly include these packages
  format: ["cjs"],
  platform: "node",
  dts: false,
  sourcemap: true,
  clean: true,
  minify: false,
});
